//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildDeployWpf.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildDeployWpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] buildeploy {
            get {
                object obj = ResourceManager.GetObject("buildeploy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] buildeploy1 {
            get {
                object obj = ResourceManager.GetObject("buildeploy1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a [
        ///  {
        ///    &quot;id&quot;: 1,
        ///    &quot;name&quot;: &quot;C#&quot;,
        ///    &quot;executableName&quot;: &quot;dotnet&quot;,
        ///    &quot;buildCommand&quot;: &quot;dotnet publish&quot;,
        ///    &quot;argumentsJson&quot;: &quot;[{\&quot;configuration\&quot;:\&quot;\&quot;},{\&quot;output\&quot;:\&quot;\&quot;}]&quot;,
        ///    &quot;isJavascriptFramework&quot;: false
        ///  },
        ///  {
        ///    &quot;id&quot;: 2,
        ///    &quot;name&quot;: &quot;Angular&quot;,
        ///    &quot;executableName&quot;: &quot;ng&quot;,
        ///    &quot;buildCommand&quot;: &quot;ng build&quot;,
        ///    &quot;argumentsJson&quot;: &quot;[{\&quot;base-href\&quot;:\&quot;\&quot;},{\&quot;prod\&quot;:\&quot;\&quot;}]&quot;,
        ///    &quot;isJavascriptFramework&quot;: true
        ///  }
        ///].
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] segoe_mdl2_assets {
            get {
                object obj = ResourceManager.GetObject("segoe-mdl2-assets", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
